import React, { useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import CustomMarkdownEditor from "../components/CustomMarkdownEditor";
import CustomMarkdownViewer from "@/components/CustomMarkdownViewer";

const Home: NextPage = () => {
  const [markdownValue, setMarkdownValue] = useState(
    "# This is a header\n\nThis is a paragraph"
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-row gap-6 items-center justify-center">
        <CustomMarkdownEditor markdownValue={markdownValue} setMarkdownValue={setMarkdownValue} />
        <CustomMarkdownViewer markdownValue={markdownValue} />
      </main>
    </>
  );
};

export default Home;
